# Generated by Django 3.0.7 on 2020-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=500)),
            ],
        ),
    ]
